### PR TITLE
changing definition of subspace, introducing new activities

### PR DESCRIPTION
**Pull request by jkostiuk**
#282

### CODE REVIEW

**Comment by jkostiuk** [comment]
If you're happy with EV3, the last thing we need here is to remove redundancies in EV7

**Comment by StevenClontz** [comment]
I've tagged Drew for a preliminary review of this PR before we update EV7 to match.

**Comment by siwelwerd** [comment]
I am okay proceeding with this and evaluating how it goes this semester.

**Comment by StevenClontz** [comment]
Then @jkostiuk and I can put a bow on this during our planned meeting tomorrow morning.

**Review by StevenClontz — APPROVED** [review]
(approving as we've already discussed changes on Zoom)

**Pull request merged**
