### PR TITLE
Generate PDF slides

### PR DESCRIPTION
**Pull request by siwelwerd**
Work in progress -- generate a PDF slideshow.

@StevenClontz Maybe download this branch, run `pretext build slides-new` and let me know what you think. 

Not yet sure if we should put this in parallel to the Reveal slides, or deprecate the Reveal slides (since they are so brittle)

### CODE REVIEW

**Comment by StevenClontz** [comment]
I say we drop the Reveal slide conversion in the 2024 edition in lieu of this.

**Comment by StevenClontz** [comment]
I'm spinning this up now to try out.

**Comment by StevenClontz** [comment]
I patched on a couple commits so this will be the "official" slide solution.

- Todo: remove the slideshow preface in the book.
- Eventually: when 2024 edition goes out, the homepage `site/index.html` should provide a link to slides alongside the PDF link.

**Comment by siwelwerd** [comment]
Sounds good. I'll proceed with tweaking the formatting, with a goal of having this deployed in the early edition for spring semester (both here and in the Calculus).

Is there a good way to share the xsl file between the two (eventually more) projects?  There may be a few lines that need to be different, but for a consistent presentation the bulk of the file should be the same.

**Comment by StevenClontz** [comment]
> Is there a good way to share the xsl file

Not really. I've pondered whether we should move to a "monorepo" pattern, where every book in our library is tracked in the same repository. Then it could literally be the same file, perhaps with some `param`s to tweak for each book. So keep me posted if you think that would be helpful for you or others.

**Comment by siwelwerd** [comment]
I think a monorepo might be confusing to our authors. There's always a hesitancy to not want to break things--while I know the workflow is set up so that this is almost impossible, and always recoverable, people still have that hesitancy.  Having multiple books in there might exacerbate this

Maybe a solution would be to have a common-files repo for any of these common presentation files, and then just copy those files over to each book.

**Comment by StevenClontz** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Submodules is a thing, but I think it's rarely used for a reason

**Comment by siwelwerd** [comment]
Ending my work week by marking this as ready for @StevenClontz to review next week.  This will close #252 #167 #148, and I think #80 (since multipart activities are not displayed sequentially here, but all at once).

**Review by StevenClontz — APPROVED** [review]
I'm not sure if it was intentional, but this changes the font size of the regular activity book to 14pt as well. I think I might like that? In any case, it can be reverted later.

Looks great, thanks for running forward with this Drew - I can finally rest easy knowing my mediocre Reveal conversion is no longer being depended on.

**Comment by siwelwerd** [comment]
Oops.  No, that wasn't intentional, that change was made here
https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/12d3f3029569442e95308ec21744a143a1e6405e/publication/publication.ptx#L42

I guess if we want them different, we need to duplicate publication.ptx, and set the `@publication` attribute for the `slides` target in project.ptx?

**Comment by StevenClontz** [comment]
Yep. Unfortunately there's no way at the moment to "tweak" a publication file - you have to maintain two copies even if they're very similar.

**Pull request merged**
