### PR TITLE
Fix 2024 edition links

### LINKED ISSUE #339: Slideshow and exercise links are out-of-date
I believe most (all?) of the slideshow and exercise links point to the 2023 versions in the current public version of the text

### PR DESCRIPTION
**Pull request by siwelwerd**
Closes #339

### CODE REVIEW

**Comment by siwelwerd** [comment]
Ah, that makes sense.  See [here](https://github.com/TeamBasedInquiryLearning/linear-algebra/issues/345#issuecomment-1911056320) for the one-liner I used to change the links in all the source files.

**Comment by StevenClontz** [comment]
`sed` is dark magic - I just used VS Code search/replace 😅 (my preference for manual fixes, though the `sed` approach is better if we want to script this)

**Review by StevenClontz — CHANGES_REQUESTED** [review]
change 2024e to 2024

**Comment by StevenClontz** [comment]
I'm working on hotfix at https://github.com/TeamBasedInquiryLearning/linear-algebra/tree/2024e-hotfix - note this won't be merged into main as I'm just doing this to get a clean 2024e build, and will then update the archive on main.

**Comment by StevenClontz** [comment]
Also, a subtlety that's a bit of a meme in PreTeXt circles, but we're talking about "editions", not "versions". Editions are timed releases, while versions are things like "student version", "instructor version", etc.

**Review by StevenClontz — APPROVED** [review]

**Pull request merged**
