### PR TITLE
Worksheet

### PR DESCRIPTION
**Pull request by siwelwerd**
@fragandi Asked for worksheets which contained the activities, with no white space like the slides. This produces a mockup of what this might look like.  

Currently, the numbering is broken -- the activities are pulled in and numbered sequentially, rather than the counter incrementing for the omitted things (facts, definitions, etc.). As a result, the numbers do not match the HTML.

### CODE REVIEW

**Comment by siwelwerd** [comment]
[TBIL-LA-2024-worksheet.pdf](https://github.com/TeamBasedInquiryLearning/linear-algebra/files/13137381/TBIL-LA-2024-worksheet.pdf)

@fragandi Take a look at this and let me know what you think before I put any effort into getting the numbering working.

**Comment by siwelwerd** [comment]
Noting that the request is also for the LaTeX that generates these worksheets.

**Comment by siwelwerd** [comment]
@fragandi Download this branch, run `pretext worksheet-slides`, and take a look at the generated LaTeX file in output/worksheet-latex .

**Comment by siwelwerd** [comment]
Asked for help fixing the numbering problem here: https://groups.google.com/g/pretext-support/c/kosEJK6mVZw/m/_2j_i6X1AQAJ

**Comment by siwelwerd** [comment]
Open to a possible refactoring of the XSL in the future if anyone has clever ideas, but this produces the desired output.

**Comment by siwelwerd** [comment]
I did end up refactoring this. I think this will be less brittle.  I think the *right* solution here involves a patch to PreTeXt itself, but maybe this will be good enough for @fragandi's use.

**Review by StevenClontz — APPROVED** [review]
Sorry for the delay. I updated to the latest changes in main and was able to build. It passes the eyeball test; the only hesitation is that it's more XSL to maintain...

**Comment by StevenClontz** [comment]
Will let @siwelwerd squash and merge if he takes this responsibility... :-)

**Pull request merged**
